### ISSUE TITLE
The `publish` badge on the home page is marked as failing

### ISSUE THREAD

**Issue by msto** [fulcrumgenomics/prymer#24] opened 2024-09-18 17:36 UTC
Two issues here, I think

1. The badget links to a search for an action named "Python package", of which we have none.

https://github.com/fulcrumgenomics/prymer/actions?query=workflow%3A%22Python+package%22

2. I assume the badge is meant to be linked to the "publish" action, but this action also appears to be broken (at least, the most recent execution failed, and so I'm assuming Nils manually published)

https://github.com/fulcrumgenomics/prymer/actions/workflows/publish.yml

**Comment by clintval** [comment] 2024-09-18 18:14
Duplicate of https://github.com/fulcrumgenomics/prymer/issues/3

I think I know what's happening. I believe the trust relationship was copied verbatim from pybedlite when we drafted https://github.com/fulcrumgenomics/pybedlite/pull/37. I'll co-assign myself and see if I can't figure it out.

**Closed** 2024-09-19 16:28 UTC
